version: "3.8"

services:
  nvidia-cuda:
    image: nvidia/cuda:12.3.0-base-ubuntu22.04
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: nvidia-smi
