attention_head_size: 3
categorical_groups: {}
causal_attention: true
dataset_parameters:
  add_encoder_length: true
  add_relative_time_idx: true
  add_target_scales: false
  allow_missing_timesteps: false
  categorical_encoders:
    __group_id__group_id: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        ? !!python/object/apply:numpy._core.multiarray.scalar
        - &id001 !!python/object/apply:numpy.dtype
          args:
          - i8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          AQAAAAAAAAA=
        : 0
      classes_vector_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - &id002 !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id001
        - false
        - !!binary |
          AQAAAAAAAAA=
      warn: true
    group_id: !!python/object:pytorch_forecasting.data.encoders.NaNLabelEncoder
      add_nan: false
      classes_:
        ? !!python/object/apply:numpy._core.multiarray.scalar
        - *id001
        - !!binary |
          AQAAAAAAAAA=
        : 0
      classes_vector_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id001
        - false
        - !!binary |
          AQAAAAAAAAA=
      warn: true
  constant_fill_strategy: null
  group_ids:
  - group_id
  lags: null
  max_encoder_length: 1
  max_prediction_length: 287
  min_encoder_length: 1
  min_prediction_idx: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAAAAAAA=
  min_prediction_length: 287
  predict_mode: false
  randomize_length: null
  scalers:
    cos_time: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.7.0
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id004 !!python/object/apply:numpy.dtype
          args:
          - O8
          - false
          - true
          state: !!python/tuple
          - 3
          - '|'
          - null
          - null
          - null
          - -1
          - -1
          - 63
        - false
        - - cos_time
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - &id003 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          b930oBKliLw=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        YF4CAAAAAAA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          zTt/Zp6g5j8=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAA4D8=
      with_mean: true
      with_std: true
    encoder_length: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.7.0
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - encoder_length
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        YF4CAAAAAAA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAA8D8=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      with_mean: true
      with_std: true
    irradiance: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.7.0
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - irradiance
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          V54aWpl0akA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        YF4CAAAAAAA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          Vilm9nnTc0A=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          SxaXzSyR+EA=
      with_mean: true
      with_std: true
    relative_time_idx: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.7.0
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - relative_time_idx
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        YF4CAAAAAAA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAA8D8=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAAAAA=
      with_mean: true
      with_std: true
    sin_time: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.7.0
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - sin_time
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          jJFeAGOkNzw=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        YF4CAAAAAAA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          zTt/Zp6g5j8=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AAAAAAAA4D8=
      with_mean: true
      with_std: true
    temperature: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.7.0
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - temperature
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          HCyTeKDkMUA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        YF4CAAAAAAA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          gj4iOjUwGkA=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          SZV+Hp9uRUA=
      with_mean: true
      with_std: true
    wind_speed: !!python/object:sklearn.preprocessing._data.StandardScaler
      _sklearn_version: 1.7.0
      copy: true
      feature_names_in_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id004
        - false
        - - wind_speed
      mean_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          YFqzITn9GUA=
      n_features_in_: 1
      n_samples_seen_: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        YF4CAAAAAAA=
      scale_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          9vq0lpyQE0A=
      var_: !!python/object/apply:numpy._core.multiarray._reconstruct
        args:
        - *id002
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 1
        - *id003
        - false
        - !!binary |
          AQ6D7o7sN0A=
      with_mean: true
      with_std: true
  static_categoricals: null
  static_reals: null
  target: active_power
  target_normalizer: &id005 !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
    _groups: []
    _method_kwargs: {}
    center: true
    groups: null
    method: standard
    method_kwargs: {}
    norm_:
      center: !!python/object/apply:numpy._core.multiarray.scalar
      - *id003
      - !!binary |
        Ll0SRsFlyT8=
      scale: !!python/object/apply:numpy._core.multiarray.scalar
      - *id003
      - !!binary |
        OonmahX00j8=
    scale_by_group: false
    transformation: null
  time_idx: time_idx
  time_varying_known_categoricals: null
  time_varying_known_reals:
  - temperature
  - irradiance
  - wind_speed
  - sin_time
  - cos_time
  time_varying_unknown_categoricals: null
  time_varying_unknown_reals:
  - active_power
  variable_groups: null
  weight: null
dropout: 0.22
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_continuous_size: 14
hidden_continuous_sizes: {}
hidden_size: 15
learning_rate: 0.025
log_gradient_flow: false
log_interval: -1
log_val_interval: null
lstm_layers: 1
mask_bias: -1000000000.0
max_encoder_length: 1
monotone_constaints: {}
monotone_constraints: {}
optimizer: adam
optimizer_params: null
output_size: 7
output_transformer: *id005
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals: []
static_reals:
- encoder_length
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- temperature
- irradiance
- wind_speed
- sin_time
- cos_time
- relative_time_idx
time_varying_reals_encoder:
- temperature
- irradiance
- wind_speed
- sin_time
- cos_time
- relative_time_idx
- active_power
weight_decay: 0.0
x_categoricals: []
x_reals:
- encoder_length
- temperature
- irradiance
- wind_speed
- sin_time
- cos_time
- relative_time_idx
- active_power
